const PAGES = [
  // Page 1 - Presence
  [
    '--- presence ---',
    '.rpc set          set rich presence interactively',
    '.rpc load <name>  load a saved preset',
    '.rpc list         list all presets',
    '.rpc delete <n>   delete a preset',
    '.rpc off          clear presence',
    '',
    '--- auto ---',
    '.autoreact on/off           toggle auto react',
    '.autoreact emoji <emoji>    set react emoji',
    '.autoreact user <@user>     react to specific user',
    '.autoreact channel <#ch>    react in specific channel',
    '.autoreply on/off           toggle auto reply',
    '.autoreply msg <text>       set reply message',
    '.autoreply user <@user>     reply to specific user',
    '.autoreply delay <seconds>  delay before reply',
    '.copycat on <@user>         mirror user messages',
    '.copycat off                stop copycat',
    '.copycat limit <n>          stop after n times',
  ],
  // Page 2 - Typing, AFK, Cleanup
  [
    '--- typing ---',
    '.faketype <#ch>     show typing forever in channel',
    '.faketype stop      stop fake typing',
    '.typeloop <#ch>     loop typing 24/7',
    '.slowtype <text>    send text letter by letter',
    '',
    '--- afk ---',
    '.afk on/off             toggle afk',
    '.afk msg <text>         set afk message',
    '.afk status <idle/dnd>  set status when afk',
    '.afk whitelist <@user>  skip afk reply for user',
    '.afk log                see who pinged while afk',
    '',
    '--- cleanup ---',
    '.purge <n>            delete last n messages',
    '.purge all            delete all your messages',
    '.purge match <text>   delete messages with text',
    '.nuke                 delete all messages in server',
    '.delpinned            delete your pinned messages',
  ],
  // Page 3 - Logger, Nitro
  [
    '--- logger ---',
    '.spy <@user>          get dm when user sends msg',
    '.spy off <@user>      stop spying',
    '.spy list             list all spied users',
    '.snipe                show last deleted message',
    '.editsnipe            show last edited message',
    '.keyword add <word>   notify when word is said',
    '.keyword remove <w>   remove keyword',
    '.keyword list         list keywords',
    '.ghostlog on/off      notify on ghost pings',
    '.dmforward on <wh>    forward dms to webhook',
    '.dmforward off        stop dm forwarding',
    '',
    '--- nitro ---',
    '.nitrosnipe on/off       toggle nitro sniper',
    '.nitrosnipe log          see snipe attempts',
    '.nitrosnipe speed        avg claim speed',
    '.nitrosnipe check <url>  manually check gift link',
    '.boostinfo               show your boost status',
  ],
  // Page 4 - Spam, Voice
  [
    '--- spam ---',
    '.spam <n> <text>          send message n times',
    '.spam stop                stop spam',
    '.ghostping <@user>        ping then delete',
    '.massghost <#ch>          ghost ping everyone',
    '.tts <text>               send as tts',
    '.embed <text>             send styled embed',
    '.massdm <serverid> <txt>  dm all members',
    '.impersonate <@u> <text>  send as user via webhook',
    '.schedule <secs> <text>   send message after delay',
    '.schedule list            list scheduled messages',
    '.schedule cancel <id>     cancel scheduled message',
    '',
    '--- voice ---',
    '.vjoin <#vc>     join voice channel',
    '.vleave          leave voice channel',
    '.vmute on/off    toggle self mute',
    '.vdeafen on/off  toggle self deafen',
    '.vstay <#vc>     stay in vc 24/7',
    '.vstay off       stop vstay',
  ],
  // Page 5 - Social, Server
  [
    '--- social ---',
    '.userinfo <@u|id|name>  get user info',
    '.avatar <@u|id|name>    get user avatar',
    '.banner <@u|id|name>    get user banner',
    '.mutuals <@u|id>        list mutual servers',
    '.friend add <@user>     send friend request',
    '.friend remove <@user>  remove friend',
    '.friend list            list friends',
    '.block <@user>          block user',
    '.unblock <@user>        unblock user',
    '.massfriend <serverid>  friend all members',
    '',
    '--- server ---',
    '.servers                list all servers',
    '.serverleave <id>       leave a server',
    '.massleave confirm      leave all servers',
    '.inviteinfo <invite>    info about invite',
    '.joinserver <invite>    join via invite',
    '.serverinfo             current server info',
    '.membercount            member count',
    '.roles <@user>          user roles',
    '.perms <@user>          user permissions',
  ],
  // Page 6 - Fun, Settings
  [
    '--- fun ---',
    '.shrug             ¯_(ツ)_/¯',
    '.lenny             ( ͡° ͜ʖ ͡°)',
    '.tableflip         (╯°□°）╯︵ ┻━┻',
    '.unflip            ┬─┬ ノ',
    '.invisible         send invisible message',
    '.mock <text>       mOcK tExT',
    '.reverse <text>    reverse text',
    '.big <text>        regional indicator text',
    '.zalgo <text>      z̷a̸l̴g̵o̶ text',
    '.clap <text>       clap 👏 between 👏 words',
    '.spoiler <text>    wrap each letter in spoiler',
    '.ascii <text>      convert to ascii art',
    '.greentext <text>  >greentext',
    '.copypasta <text>  rAnDoM CaSe pasta',
    '',
    '--- settings ---',
    '.prefix <new>        change command prefix',
    '.status <status>     online/idle/dnd/invisible',
    '.setavatar           attach image to change avatar',
    '.setusername <name>  change username',
    '.ping                latency',
    '.uptime              how long running',
    '.restart             restart selfbot',
    '.menu                commands page 1',
    '.menu2               commands page 2  (etc.)',
  ]
];

module.exports = {
  async handle(message, pageNum) {
    const idx = (pageNum || 1) - 1;
    if (idx < 0 || idx >= PAGES.length) {
      return message.reply(`\`valid pages: 1-${PAGES.length}\``);
    }
    const lines = PAGES[idx].map(l => l ? `\`${l}\`` : '').join('\n');
    const header = `\`page ${idx + 1}/${PAGES.length} — .menu${idx + 2} for next\`\n`;
    return message.reply(header + lines);
  },
  PAGE_COUNT: PAGES.length
};
